import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function loginLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <main>
            <div className={'login_wrap'}>
                <div className={'login_block'}>{children}</div>
            </div>
        </main>
    )
}
