import type { Metadata } from 'next'
import { StoreProvider } from '@/store/StoreProvider'
import { Geist, Geist_Mono } from 'next/font/google'
import '@/styles/globals.css'
// import '@/styles/demo.css'
import '@/assets/css/reset.css'
import '@/assets/css/style.css'
import '@/assets/css/fix.css'
import '@/assets/css/map.css'
import '@/assets/css/pdf.css'
import '@/assets/js/slick/slick-theme.css'
import '@/assets/js/slick/slick.css'
import '@/assets/js/calendar/pignose.calendar.css'
import '@/assets/js/select2/select2.css'
import '@/assets/js/datetimepicker/jquery.datetimepicker.css'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body>
                <div v-if="!open" className="pending_app" style={{ height: '50vh' }}>
                    {/* <LazyAnimationLoading lg /> */}
                </div>
                <StoreProvider>{children}</StoreProvider>
            </body>
        </html>
    )
}
