import type { Metadata } from 'next'
import { StoreProvider } from '@/store/StoreProvider'
import '@/styles/globals.css'
// import '@/styles/demo.css'
import '@/assets/css/reset.css'
import '@/assets/css/style.css'
import '@/assets/css/fix.css'
import '@/assets/css/map.css'
import '@/assets/css/pdf.css'
import '@/assets/js/slick/slick-theme.css'
import '@/assets/js/slick/slick.css'
import '@/assets/js/calendar/pignose.calendar.css'
import '@/assets/js/select2/select2.css'
import '@/assets/js/datetimepicker/jquery.datetimepicker.css'

import Script from 'next/script'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <head>
                <Script src="/js/jquery-3.7.1.min.js" strategy="beforeInteractive" defer />
                <Script src="/js/common.js" strategy="beforeInteractive" defer />
                <Script src="/js/flexibility.js" strategy="beforeInteractive" defer />
            </head>
            <body>
                <StoreProvider>{children}</StoreProvider>
                <Script src="/js/slick/slick.min.js" strategy="afterInteractive" defer />
                <Script src="/js/jquery.matchHeight.js" strategy="afterInteractive" defer />
                <Script src="/js/Sortable.min.js" strategy="afterInteractive" defer />
                <Script src="/js/select2.min.js" strategy="afterInteractive" defer />
                <Script src="/js/jquery.datetimepicker.full.min.js" strategy="afterInteractive" defer />
            </body>
        </html>
    )
}
